modLoader = "javafml"
loaderVersion = "0"
issueTrackerURL = "${modIssueUrl}"
license = "${modLicense}"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modDisplayName}"
authors = "${modAuthors}"
displayURL = "${modDisplayUrl}"
description = '''${modDescription}'''
logoFile = "icon.png"
logoBlur = false

[[dependencies."${modId}"]]
modId = "forge"
mandatory = true
versionRange = "0"
ordering = "NONE"
side = "BOTH"

[[dependencies."${modId}"]]
modId = "minecraft"
mandatory = true
versionRange = "0"
ordering = "NONE"
side = "BOTH"

[[dependencies."${modId}"]]
modId = "valkyrienskies"
mandatory = true
versionRange = "0"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${modId}"]]
modId = "cloth_config"
mandatory = true
versionRange = "0"
ordering = "NONE"
side = "BOTH"
